version: 2.1
orbs:
  hello: etgrieco/hello-world@dev:0.0.1

jobs:
  sleep:
    docker:
      - image: circleci/node
    steps:
      - run: sleep 60

workflows:
  orb-test:
    jobs:
      - sleep
      - hello/pyscript
