version: 2.1
orbs:
  hello: etgrieco/hello-world@dev:0.0.1

workflows:
  orb-test:
    jobs:
      - hello/pyscript
    # triggers:
    #   - schedule:
    #       cron: 5,10,15,20,25,30,35,40,45,50,55 * * * *
    #       filters:
    #           branches:
    #             only:
    #               - master
