version: 2.1

orbs:
  hello: etgrieco/hello-world@dev:0.0.1

jobs:
  build:
    executor: hello/default
    steps:
      - hello/sayhellotomyfriend:
          friend: Anna

workflows:
  test-orb:
    triggers:
      - schedule:
          cron: 5,10,15,20,25,30,35,40,45,50,55 * * * *
          filters:
              branches:
                only:
                  - master
    jobs:
      - build
