version: 2.1
orbs:
  hello: etgrieco/hello-world@dev:0.0.1

jobs:
  docker:
    - image: circleci/node
  sleep:
    steps:
      - sleep 1000

workflows:
  orb-test:
    jobs:
      - sleep
      - hello/pyscript
