version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/app/
    steps:
      - checkout
      - run:
          name: Install python dependencies
          command: pip install requests
      - run:
          name: Run monitor script
          command: python ~/app/app.test.py

workflows:
  test-orb:
    # triggers:
    #   - schedule:
    #       cron: 5,10,15,20,25,30,35,40,45,50,55 * * * *
    #       filters:
    #           branches:
    #             only:
    #               - master
    jobs:
      - build
