version: 2.1

orbs:
  hello: etgrieco/hello-world@dev:0.0.1

jobs:
  build:
    docker:
      - image: circleci/alpine
    steps:
      - hello/sayhellotomyfriend:
          friend: Anna

workflows:
  test-orb:
    jobs:
      - build
